# Generated by Django 2.2.15 on 2020-08-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200811_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.Category', verbose_name='父级分类id'),
        ),
    ]
