# Generated by Django 2.2.15 on 2020-08-12 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200811_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间'),
        ),
    ]
